// DO NOT MODIFY, FILE AUTOMATICALLY GENERATED ON BUILD (utilities/rebuild_mains.js)

// If you want to modify an unit, please do so in watteco-bacnet-mapping.csv
// If you want to add a variable, please do so in ClustersVariables.json

// After modifying/adding anything, please run "node utilities/rebuild_mains.js" to update the units.auto.js file

let units = {
    "main_or_external_voltage": "V",
    "positive_active_energy_a": "kWh",
    "positive_active_energy_b": "kWh",
    "positive_active_energy_c": "kWh",
    "positive_active_energy_abc": "kWh",
    "negative_active_energy_a": "kWh",
    "negative_active_energy_b": "kWh",
    "negative_active_energy_c": "kWh",
    "negative_active_energy_abc": "kWh",
    "positive_reactive_energy_a": "kVArh",
    "positive_reactive_energy_b": "kVArh",
    "positive_reactive_energy_c": "kVArh",
    "positive_reactive_energy_abc": "kVArh",
    "negative_reactive_energy_a": "kVArh",
    "negative_reactive_energy_b": "kVArh",
    "negative_reactive_energy_c": "kVArh",
    "negative_reactive_energy_abc": "kVArh",
    "positive_active_power_a": "W",
    "positive_active_power_b": "W",
    "positive_active_power_c": "W",
    "positive_active_power_abc": "W",
    "negative_active_power_a": "W",
    "negative_active_power_b": "W",
    "negative_active_power_c": "W",
    "negative_active_power_abc": "W",
    "positive_reactive_power_a": "VAr",
    "positive_reactive_power_b": "VAr",
    "positive_reactive_power_c": "VAr",
    "positive_reactive_power_abc": "VAr",
    "negative_reactive_power_a": "VAr",
    "negative_reactive_power_b": "VAr",
    "negative_reactive_power_c": "VAr",
    "negative_reactive_power_abc": "VAr",
    "Vrms_a": "V",
    "Vrms_b": "V",
    "Vrms_c": "V",
    "Irms_a": "A",
    "Irms_b": "A",
    "Irms_c": "A",
    "angle_a": "deg",
    "angle_b": "deg",
    "angle_c": "deg",
    "active_energy_a": "kWh",
    "reactive_energy_a": "kVArh",
    "active_energy_b": "kWh",
    "reactive_energy_b": "kVArh",
    "active_energy_c": "kWh",
    "reactive_energy_c": "kVArh",
    "active_energy_abc": "kWh",
    "reactive_energy_abc": "kVArh",
    "active_power_a": "W",
    "reactive_power_a": "VAr",
    "active_power_b": "W",
    "reactive_power_b": "VAr",
    "active_power_c": "W",
    "reactive_power_c": "VAr",
    "active_power_abc": "W",
    "reactive_power_abc": "VAr"
}

module.exports = units;